/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as disperseSol from "./Disperse.sol";
export type { disperseSol };
import type * as multicallSol from "./Multicall.sol";
export type { multicallSol };
export type { Token } from "./Token";
