/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DisperseInterface extends Interface {
  getFunction(
    nameOrSignature: "disperseEther" | "disperseToken" | "disperseTokenSimple"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "disperseEther",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "disperseToken",
    values: [AddressLike, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "disperseTokenSimple",
    values: [AddressLike, AddressLike[], BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "disperseEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disperseToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disperseTokenSimple",
    data: BytesLike
  ): Result;
}

export interface Disperse extends BaseContract {
  connect(runner?: ContractRunner | null): Disperse;
  waitForDeployment(): Promise<this>;

  interface: DisperseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  disperseEther: TypedContractMethod<
    [recipients: AddressLike[], values: BigNumberish[]],
    [void],
    "payable"
  >;

  disperseToken: TypedContractMethod<
    [token: AddressLike, recipients: AddressLike[], values: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  disperseTokenSimple: TypedContractMethod<
    [token: AddressLike, recipients: AddressLike[], values: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "disperseEther"
  ): TypedContractMethod<
    [recipients: AddressLike[], values: BigNumberish[]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "disperseToken"
  ): TypedContractMethod<
    [token: AddressLike, recipients: AddressLike[], values: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disperseTokenSimple"
  ): TypedContractMethod<
    [token: AddressLike, recipients: AddressLike[], values: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  filters: {};
}
