/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as disperseSol from "./Disperse.sol";
export type { disperseSol };
import type * as multicallSol from "./Multicall.sol";
export type { multicallSol };
export * as factories from "./factories";
export type { Disperse } from "./Disperse.sol/Disperse";
export { Disperse__factory } from "./factories/Disperse.sol/Disperse__factory";
export type { IERC20 } from "./Disperse.sol/IERC20";
export { IERC20__factory } from "./factories/Disperse.sol/IERC20__factory";
export type { Multicall3 } from "./Multicall.sol/Multicall3";
export { Multicall3__factory } from "./factories/Multicall.sol/Multicall3__factory";
